### PR TITLE
Python 3.4

### PR DESCRIPTION
**Pull request by montefra**
First steps towards python3, as requested [here](https://github.com/ericmandel/pyds9/pull/14)

Now you can import it, but it doesn't work yet.

Hopefully it won't take long

### CODE REVIEW

**Comment by montefra** [comment]
I didn't noticed until now that there was already pull request #1 open :(

**Comment by ericmandel** [comment]
Ah yes, sorry, I forgot about that. It's current status is unclear to me. Perhaps @cdeil will comment.

**Comment by montefra** [comment]
@ericmandel: I've switched urllib for [requests](http://www.python-requests.org/en/latest/).

I can run

```
j = JS9('js9.si.edu')
```

But then I cannot do anything else. I've tried with the version on master and on my python3 branch, both with python 2 and 3 and I always get: `ValueError: ERROR: 0 JS9 instance(s) found with id JS9 (...)`.

I don't have a server with js9 runnint. Can you please test if the code works on python3?

Travis failure has nothing to do with me. It is because I don't have the `.travis.yml`.

**Comment by ericmandel** [comment]
@montefra 

>  I always get: ValueError: ERROR: 0 JS9 instance(s) found with id JS9 (...).

Do you have the http://js9.si.edu Web page actually displayed in a browser? The error indicates that you do not ... or else there is a problem I haven't seen before.

I will test python3 but I have to write most of a talk by Monday, so I might not get to it immediately.

**Comment by montefra** [comment]
:blush: no I didn't have the page open...

Now the communication works. I just have to fix issues with the byte strings. You should get a new commit fixing it

**Comment by ericmandel** [comment]
@montefra And I'll be able to merge the JS9 PR more quickly than the PR for DS9, since pyjs9 is still in its infancy and (unfortunately) not heavily used. We probably need to wait a bit on the DS9 PR to see if anyone has comments ... but not too long.

**Comment by montefra** [comment]
@ericmandel: ok.

If you decide to merge my PR, probably would make sense to cherrypick and if necessary adapt @cdeil commits about travis and tests.

**Comment by ericmandel** [comment]
@montefra Yes, I'll have to think about that. We can always add that stuff back later. Some of that functionality I eventually implemented using selenium locally, much easier for me. Anyway ...

**Comment by montefra** [comment]
With commit ab86b70 I can run the example in the readme file on python 2 and 3.

@ericmandel gotcha. Good night and enjoy python 3 :smile:

**Comment by ericmandel** [comment]
Thanks so much, it's really appreciated! Give me a few days and we'll get this finished.

**Comment by cdeil** [comment]
@montefra - Thanks!

**Comment by montefra** [comment]
@cdeil a pleasure.

As for my [pyds9 PR](https://github.com/ericmandel/pyds9/pull/14) I would like to review my changes to see if there are better ways to do string <--> conversions before merging.

**Comment by ericmandel** [comment]
@montefra I finally am getting back to pyjs9. I merged your PR -- thanks very much for doing the work. I hope I will have time to look into integrating python socket.io this week. Also need to add some public API calls that have been added to JS9 since the last pyjs9 release.

I'd like to undo thr travis-cl checks (at least for now). Can you please tell me how to do that?

**Comment by montefra** [comment]
@ericmandel: thank you. I hope that my code is good enough.

About Travis: I don't have an account, but guessing from the screenshot in [this issue](https://github.com/travis-ci/travis-ci/issues/987) there is some way to enable and disable repos. I hope that this is good enough.

**Comment by ericmandel** [comment]
Thanks, I think I managed to turn of the travis-cl test ... we can re-enable it later.

**Pull request merged**
